name: Compile Test

on:
  - pull_request
jobs:
  compile_project:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with: 
          # Search the root dir for projects
          sketch-paths: |
            - ./
          
          # No libraries needed
          libraries: |
            - 
