name: Compile Test

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"
jobs:
  compile_project:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with: 
          # Search the root dir for projects
          sketch-paths: |
            - ./
          
          # Required libraries
          libraries: |
            - name: TinyGPSPlus
            - name: RF24
            - name: DHT sensor library
            - name: OneWire
            - name: DallasTemperature
            - name: Time
