on:
  - pull_request
jobs:
  compile_project:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: arduino/compile_sketches@v1
        with: 
          sketch_paths : |
            - ./
